-- MySQL Script generated by MySQL Workbench
-- Tue 04 Jul 2017 02:22:23 PM EDT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ulbora_image_service
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ulbora_image_service
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ulbora_image_service` DEFAULT CHARACTER SET utf8 ;
USE `ulbora_image_service` ;

-- -----------------------------------------------------
-- Table `ulbora_image_service`.`image`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ulbora_image_service`.`image` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `size` INT NOT NULL,
  `file_extension` VARCHAR(5) NOT NULL,
  `file_data` LONGBLOB NOT NULL,
  `client_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
